---
- name: Add Docker CE repository for containerd
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
  when: ansible_distribution != 'Amazon'

- name: Install containerd (Amazon Linux native package)
  ansible.builtin.dnf:
    name: containerd
    state: present
  when: ansible_distribution == 'Amazon'

- name: Install containerd (Docker CE containerd.io)
  ansible.builtin.dnf:
    name: containerd.io
    state: present
  when: ansible_distribution != 'Amazon'
