---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc-rbac
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/T-CLO-902-KubeQuest/KubeQuest.git
    targetRevision: main
    path: k8s/oidc-rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
