---
# ansible/roles/kubernetes_worker_join/tasks/main.yml

- name: "Check if the worker node is already part of the cluster"
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf
  tags: [ 'check_state' ]

- name: "Dynamically retrieve join command from the control-plane (kube-1)"
  ansible.builtin.command: kubeadm token create --print-join-command
  register: kubernetes_join_command
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  when: not kubelet_conf.stat.exists
  changed_when: false
  # Note: Task is delegated to the first host in 'control_plane' group (kube-1)
  # run_once prevents overloading the master if multiple workers are being joined
  tags: [ 'get_token' ]

- name: "Join the worker node to the Kubernetes cluster"
  ansible.builtin.command: "{{ kubernetes_join_command.stdout }}"
  when: not kubelet_conf.stat.exists and kubernetes_join_command is defined and kubernetes_join_command.stdout is defined
  # Join command is only executed if kubelet.conf is missing (idempotency)
  tags: [ 'join_cluster' ]

- name: "Confirm join status"
  ansible.builtin.debug:
    msg: "Worker node has already joined the cluster or has just finished joining."
  when: kubelet_conf.stat.exists
  tags: [ 'check_state' ]
