---
- name: Prepare Linux nodes for Kubernetes
  hosts: aws_ec2
  gather_facts: true
  become: true
  roles:
    - common

- name: Configure container runtime
  hosts: aws_ec2
  become: true
  gather_facts: true
  roles:
    - container-runtime

- name: Install Kubernetes tooling on cluster nodes
  hosts: aws_ec2
  become: true
  gather_facts: true
  tags: kubeadm
  roles:
    - kubeadm
