---
container_runtime_arch_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf
container_runtime_arch: "{{ container_runtime_arch_map[ansible_architecture] }}"

container_runtime_systemd_cgroup: true
container_runtime_sandbox_image: "registry.k8s.io/pause:3.9"
